### ISSUE TITLE
How to reconnect

### ISSUE THREAD

**Issue by aokihu** [Yongke/luamqttc#3]
Hi, does it can reconnect server automatic?

**Comment by damody** [comment]
do reconnect  when you get error by modify client.lua local assert function.

**Comment by Yongke** [comment]
Let it crash ;-) This experience some how comes from Erlang. 

In our production environment, which is mqtt client for `Openwrt`, subscriber client is supervised by `runit`. When client disconnects/crashes, it will be automatically restarted.  And as publisher, we send message out on new connection.

For us, this pattern works stable and well. Hope it helps.

**Comment by aokihu** [comment]
Hey, my suggestion is that it will be better to reconnect  when connect lost by manually
