### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by roman65536** [Yongke/luamqttc#4]
Hi,
I receive from time to time timeout errors and I'm not sure why.
lua: /usr/local/share/lua/5.1/luamqttc/client.lua:19: error message: timeout
stack traceback:
        [C]: in function 'gassert'
        /usr/local/share/lua/5.1/luamqttc/client.lua:19: in function 'assert'
        /usr/local/share/lua/5.1/luamqttc/client.lua:279: in function 'keepalive'
        /usr/local/share/lua/5.1/luamqttc/client.lua:271: in function 'cycle_packet'
        /usr/local/share/lua/5.1/luamqttc/client.lua:146: in function 'message_loop'
        heiz2.lua:79: in main chunk
        [C]: ?

Could you point me or give me some hints?

regards
Roman

**Comment by Yongke** [comment]
Hi, Roman

Can you please use the latest code from master branch and try again? Which I can find more info from stack.

Better to have your code clip ;-)

**Comment by roman65536** [comment]
Just build it, so let me check with master branch first.

**Comment by roman65536** [comment]
Same thing with latest branch:
outTopic/sensor/pir/7->0
8:5
outTopic/sensor/temp/0->13.1
8:5
13
ref/temp
13
outTopic/sensor/humi/0->45lua: /usr/local/share/lua/5.1/luamqttc/client.lua:19: error message: timeout
stack traceback:
        [C]: in function 'gassert'
        /usr/local/share/lua/5.1/luamqttc/client.lua:19: in function 'assert'
        /usr/local/share/lua/5.1/luamqttc/client.lua:279: in function 'keepalive'
        /usr/local/share/lua/5.1/luamqttc/client.lua:271: in function 'cycle_packet'
        /usr/local/share/lua/5.1/luamqttc/client.lua:146: in function 'message_loop'
        heiz2.lua:79: in main chunk
        [C]: ?
.3
8:5
outTopic/sensor/pir/0->0
8:5
outTopic/sensor/temp/1->12.7
8:5
13
ref/temp1
nil

Here the code, it does regulate temperature depending on current ambient temperature. Which message to looking for and what is the relay, is in the xml config file. So far there is lot of prints for debuging.

Code:

xpath= require "xpath"
local lom = require "lxp/lom"
local mqttclient = require("luamqttc/client")

local ref_temp=10.0

local temp_hyst=.4

local f = assert(io.open("test2.xml", "r"))
local t = f:read("*all")
    
sensors=xpath.selectNodes(lom.parse(t),'/config/heiz/sensor/')
print(#sensors)
relay={}
ref={}
ref_t={}
for a=1,#sensors do
if (sensors[a]["attr"]["relay"] ~= nil) then  print (sensors[a]["attr"]["id"].." "..sensors[a]["attr"]["relay"] ) end
relay[sensors[a]["attr"]["id"]]=sensors[a]["attr"]["relay"]
ref[sensors[a]["attr"]["id"]]=sensors[a]["attr"]["ref"]
end    


for a,b in pairs(relay) do
 print(a.." "..b)
 end
 
for a,b in pairs(ref) do
 print(a.." "..b)
 end
 
 print(mqttclient)
cl=mqttclient.new("myclient")
host="192.168.0.90"
timeout=2
cl:connect(host,1883,{timeout=timeout})
 
function callbc(topic,data)
if (topic == "ref/temp") then ref_temp=tonumber(data) print("New Reference Temperature set to "..ref_temp) end

for a,b in pairs(ref) do
if(topic == b) then ref_tmp=tonumber(data) print("New Temperature for "..topic.." set to "..ref_tmp) ref_t[topic]=ref_tmp end
end

print(topic.."->"..data)
t=os.date('*t')
print(t.hour..":"..t.min)
if (relay[topic] ~= nil ) then 
--print ("Found it "..relay[topic])  

--if((t.hour>8) and (t.hour <18) ) then flag=0
-- else flag=1 end
flag=1


print(ref_temp)
print(ref[topic])
print(ref_t[ref[topic]])
if ( ref_t[ref[topic]] ~= nil ) then
if ((tonumber(data)+temp_hyst < ref_t[ref[topic]]) and (flag == 1)) then 
 print(cl:publish(relay[topic],"on"))
print(string.format("%d:%d : %s %s Turning on",t.hour,t.min,topic,relay[topic]))
 elseif ((tonumber(data)-temp_hyst > ref_t[ref[topic]]) and (flag == 1)) then
  print(cl:publish(relay[topic],"off"))
  print(string.format("%d:%d : %s %s Turning off",t.hour,t.min,topic,relay[topic]))
  -- print(t..":.."Turning off")
 end
 end
end
--print(topic)
end
 
 
 
cl:subscribe("#",2,callbc)


while (1) do
cl:message_loop(15)
end

**Comment by roman65536** [comment]
Yongke,
there is something wrong with send function.
When the timer runs out, it won't let send any messages out and returns always "timeout". 
You probable know better what those timer are, what they are for. 
Changing keepalive function slidly and all works again. 

roman

```

_M.send = function(self, data)
    local remain = self.timer:remain()
    if remain < 0 then
        return nil, "timeout"    -- This is where it returns timeout without sending out ping and later on crashes.
    end
    self.transport:settimeout(remain)

    -- reset the keepalive timeout
    self:setkatimeout()

    return self.transport:send(data)
end
```

```
_M.keepalive = function(self)
    if self.keepalive_timer:remain() < 0 then
 print(self.keepalive_timer:remain() )
        local data = mqttpacket.serialize_pingreq()
        local ok, err = self:send(data)
 print(ok)
 print(err)
        if (err == "timeout") then
        ok,err= self.transport:send(data)
         print(ok)
         print(err)
        end

        assert(ok, err)
        self.pingresp_timer = timer.new(5)
    end
end
```

**Comment by Yongke** [comment]
You are correct. function `keepalive` should not invoke `send` wrapper. 
change below would be nice. 

``` lua
_M.keepalive = function(self)
    if self.keepalive_timer:remain() < 0 then
        local data = mqttpacket.serialize_pingreq()
        self:setkatimeout()
        local ok, err = self.transport:send(data)
        assert(ok, err)
        self.pingresp_timer = timer.new(5)
    end
end
```
Would you please try this patch again? If no problem, I will commit the change. 
Thanks very much.

**Comment by roman65536** [comment]
Will let you know next 24 hours or so.
thank you 

After almost 12 hours non stop, look like you nail it.
Still working good after almost 24 hours, I think you can commit the change and close this issue.

thx and regads
roman

**Comment by roman65536** [comment]
Yongke,

you can commit, it works now for 2 days non stop without a glitch.

**Comment by Yongke** [comment]
Change committed. Thanks for your feedback.
